#!/usr/bin/env python3
"""
org_query.py — Skill wrapper for ~/.hermes/scripts/org_query.py.

This file is a thin re-export of the canonical script at ~/.hermes/scripts/org_query.py.
Do NOT edit this file directly — edit ~/.hermes/scripts/org_query.py instead.
"""

import os
import sys

# Canonical script location
CANONICAL_PATH = os.path.expanduser('~/.hermes/scripts/org_query.py')

if not os.path.exists(CANONICAL_PATH):
    print(f'{{"error": "Canonical script not found: {CANONICAL_PATH}"}}')
    sys.exit(1)

# Delegate to the canonical script
sys.argv[0] = CANONICAL_PATH
with open(CANONICAL_PATH) as f:
    exec(compile(f.read(), CANONICAL_PATH, 'exec'))
